require('autocmds')
require('keymapping')
require('options')

require('plugins')

require('plugin-settings.bufferline')
require('plugin-settings.cmp')
require('plugin-settings.colorizer')
require('plugin-settings.comment')
require('plugin-settings.gitsigns')
require('plugin-settings.glow')
require('plugin-settings.hop')
require('plugin-settings.jabs')
require('plugin-settings.lualine')
require('plugin-settings.navbuddy')
require('plugin-settings.nvim-notify')
require('plugin-settings.neo-tree')
require('plugin-settings.project')
require('plugin-settings.telescope')
require('plugin-settings.treesitter')

require('plugin-settings.lsp.lspconfig')
require('plugin-settings.lsp.lspsaga')
require('plugin-settings.lsp.null-ls')

require('plugin-settings.colors.catppuccin')
--require('plugin-settings.colors.gruvbox')
